security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_COMPANY: ROLE_USER
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        dashboard:
            pattern: ^/
            user_checker: App\EventSubscriber\UserChecker
            access_denied_handler: App\EventListener\AccessDeniedListener
            lazy: true
            provider: app_user_provider
            context: dashboard
            form_login:
                login_path: dashboard_login
                check_path: dashboard_login
                default_target_path: dashboard_my_account
                enable_csrf: true
            logout:
                path: dashboard_logout
                target: dashboard_login
    access_control:
        #  ROLE_CLIENT
        - { path: ^/dashboard/my-account, roles: [ROLE_ADMIN, ROLE_COMPANY, ROLE_CLIENT] }
        - { path: ^/dashboard/favorites, roles: [ROLE_ADMIN, ROLE_COMPANY, ROLE_CLIENT] }
        - { path: ^/dashboard/ajax/profile, roles: [ROLE_ADMIN, ROLE_COMPANY, ROLE_CLIENT] }
        - { path: ^/dashboard/cache/clear, roles: [ROLE_ADMIN, ROLE_COMPANY, ROLE_CLIENT] }

        #  ROLE_ADMIN
        - { path: ^.*/actions/remove/.+$, roles: ROLE_ADMIN }
        - { path: ^/dashboard/category, roles: ROLE_ADMIN }
        - { path: ^/dashboard/setting, roles: ROLE_ADMIN }
        - { path: ^/dashboard/language, roles: ROLE_ADMIN }
        - { path: ^/dashboard/user, roles: ROLE_ADMIN }
        - { path: ^/dashboard/page, roles: ROLE_ADMIN }
        - { path: ^/dashboard/menu, roles: ROLE_ADMIN }
        - { path: ^/dashboard/review, roles: ROLE_ADMIN }
        - { path: ^/dashboard/event, roles: ROLE_ADMIN }
        - { path: ^/dashboard/rebuild-search, roles: ROLE_ADMIN }
        - { path: ^/dashboard/ajax/admin, roles: ROLE_ADMIN }

        #  ROLE_ADMIN && ROLE_COMPANY
        - { path: ^/dashboard, roles: [ROLE_ADMIN, ROLE_COMPANY] }
        - { path: ^/, roles: PUBLIC_ACCESS }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
