twig:
    file_name_pattern: '*.twig'

    globals:
        default_locale: "%default_locale%"
        app_page_path: '%app_page_path%'
        cookiebot_id: '%cookiebot_id%'
        payu_merchant_code: '%payu_merchant_code%'
        app_education_path: '%app_education_path%'
        app_team_member_path: '%app_team_member_path%'
        app_article_path: '%app_article_path%'
        app_categories_path: '%app_categories_path%'
        app_certificate_path: '%app_certificate_path%'
        app_menu_path: '%app_menu_path%'
        app_user_photo_path: '%app_user_photo_path%'
        recaptcha_site_key: '%recaptcha_site_key%'
        recaptcha_secret_key: '%recaptcha_secret_key%'
        google_pay_merchant_id: '%google_pay_merchant_id%'
        app_gallery_path: '%app_gallery_path%'
        app_diploma_path: '%app_diploma_path%'
        intercom_app_id: '%intercom_app_id%'
        intercom_hash: '%intercom_hash%'
        onesignal_app_id: '%onesignal_app_id%'
        onesignal_safari_web_id: '%onesignal_safari_web_id%'
        settingService: '@App\Service\SettingService'
        languageHelper: '@App\Helper\LanguageHelper'
        defaultHelper: '@App\Helper\DefaultHelper'
        menu_helper: '@App\Helper\MenuHelper'

when@test:
    twig:
        strict_variables: true
