hwi_oauth:
  resource_owners:
    any_name:
      type:                 google
      client_id:            "%env(OAUTH_GOOGLE_WEB_ID)%"
      client_secret:        "%env(OAUTH_GOOGLE_WEB_SECRET)%"
      scope:                "email profile"
      options:
        csrf: true
        refresh_on_expire: true
        state:
          some: parameter
          some-other: parameter