security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  role_hierarchy:
    ROLE_USER: ROLE_USER
    ROLE_ADMIN: ROLE_USER

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      user_checker: App\Event\UserChecker
      lazy: true
      provider: app_user_provider
      context: frontend
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: app_home
        enable_csrf: true
      logout:
        path: app_logout
      oauth:
        resource_owners:
          facebook: "/login/check-facebook"
          google: "/login/check-google"
        login_path: /login
        use_forward: false
        failure_path: /login
        oauth_user_provider:
          service: my.oauth_aware.user_provider.service


  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/connect, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
