parameters:
    app_name: '%env(APP_NAME)%'
    app_env: '%env(APP_ENV)%'
    mailchimp_api_key: '%env(MAILCHIMP_API_KEY)%'
    mailchimp_api_server_prefix: '%env(MAILCHIMP_API_SERVER_PREFIX)%'
    mailchimp_list_id: '%env(MAILCHIMP_LIST_ID)%'
    email_address: '%env(EMAIL_ADDRESS)%'
    email_sender: '%env(EMAIL_SENDER)%'
    app_email: '%env(APP_EMAIL)%'
    app_default_image: '%env(APP_DEFAULT_IMAGE)%'
    app_setting_path: '%env(APP_SETTING_PATH)%'
    app_page_path: '%env(APP_PAGE_PATH)%'
    app_page_widget_path: '%env(APP_PAGE_WIDGET_PATH)%'
    app_job_path: '%env(APP_JOB_PATH)%'
    app_temporary_path: '%env(APP_TEMPORARY_PATH)%'
    app_menu_path: '%env(APP_MENU_PATH)%'
    app_course_path: '%env(APP_COURSE_PATH)%'
    app_article_path: '%env(APP_ARTICLE_PATH)%'
    app_company_path: '%env(APP_COMPANY_PATH)%'
    app_user_path: '%env(APP_USER_PATH)%'
    app_company_gallery_path: '%env(APP_COMPANY_GALLERY_PATH)%'
    default_locale: '%env(DEFAULT_LOCALE)%'
    facebook_share: '%env(FACEBOOK_SHARE)%'
    whatsapp_share: '%env(WHATSAPP_SHARE)%'
    linkedin_share: '%env(LINKEDIN_SHARE)%'
    map_share: '%env(MAP_SHARE)%'
    recaptcha_site_verify: '%env(RECAPTCHA_SITEVERIFY)%'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    excel_path: '%kernel.project_dir%/public/assets'
    cookie_bot_id: '%env(COOKIE_BOT_ID)%'
    intercom_id: '%env(INTERCOM_ID)%'
    onesignal_id: '%env(ONESIGNAL_ID)%'
    onesignal_web_id: '%env(ONESIGNAL_WEB_ID)%'
    intercom_secret_key: '%env(INTERCOM_SECRET_KEY)%'
    cloudflare_path: '%env(CLOUDFLARE_R2_FILE_PATH)%'
    elasticsearch_article_index: '%env(ELASTICSEARCH_ARTICLE_INDEX)%'
    elasticsearch_course_index: '%env(ELASTICSEARCH_COURSE_INDEX)%'
    elasticsearch_job_index: '%env(ELASTICSEARCH_JOB_INDEX)%'
    elasticsearch_company_index: '%env(ELASTICSEARCH_COMPANY_INDEX)%'
twig:
    globals:
        app_name: '%app_name%'
        app_user_path: '%app_user_path%'
        app_default_image: '%app_default_image%'
        app_setting_path: '%app_setting_path%'
        app_page_path: '%app_page_path%'
        app_page_widget_path: '%app_page_widget_path%'
        app_job_path: '%app_job_path%'
        app_menu_path: '%app_menu_path%'
        app_course_path: '%app_course_path%'
        app_article_path: '%app_article_path%'
        app_company_path: '%app_company_path%'
        app_company_gallery_path: '%app_company_gallery_path%'
        locale: '%default_locale%'
        facebook_share: '%facebook_share%'
        whatsapp_share: '%whatsapp_share%'
        linkedin_share: '%linkedin_share%'
        map_share: '%map_share%'
        recaptcha_site_key: '%recaptcha_site_key%'
        recaptcha_secret_key: '%recaptcha_secret_key%'
        cookie_bot_id: '%cookie_bot_id%'
        intercom_id: '%intercom_id%'
        onesignal_id: '%onesignal_id%'
        onesignal_web_id: '%onesignal_web_id%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Helper\DefaultHelper:
        arguments:
            $intercomSecretKey: '%intercom_secret_key%'
    App\Helper\MailHelper:
        arguments:
            $fromEmail: '%email_address%'
            $fromSender: '%email_sender%'
    App\Helper\LanguageHelper:
        arguments:
            $defaultLocale: '%default_locale%'
    App\Helper\MailchimpAPIHelper:
        arguments:
            $apiKey: '%mailchimp_api_key%'
            $serverPrefix: '%mailchimp_api_server_prefix%'
            $listId: '%mailchimp_list_id%'
    App\Command\TestElasticsearchConnectionCommand:
        arguments:
            $client: '@fos_elastica.client.default'
        tags:
            - { name: 'console.command' }
    App\Helper\ScraperHelper:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'
    App\EventListener\PageNotFoundListener:
        arguments:
            $urlGenerator: '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\Command\CompanySeedCommand:
        arguments:
            $targetDirectory: '%excel_path%'
    App\Helper\FileUploader:
        arguments:
            $slugger: '@slugger'
            $kernel: '@kernel'
            $accessKey: '%env(CLOUDFLARE_R2_ACCESS_KEY_ID)%'
            $secretKey: '%env(CLOUDFLARE_R2_SECRET_ACCESS_KEY)%'
            $region: '%env(CLOUDFLARE_R2_REGION)%'
            $endpoint: '%env(CLOUDFLARE_R2_ENDPOINT)%'
            $bucket: '%env(CLOUDFLARE_R2_BUCKET)%'
    fos_elastica.index.article:
        class: Elastica\Index
        factory: [ '@fos_elastica.client.default', 'getIndex' ]
        arguments: [ '%elasticsearch_article_index%' ]
    fos_elastica.index.course:
        class: Elastica\Index
        factory: [ '@fos_elastica.client.default', 'getIndex' ]
        arguments: [ '%elasticsearch_course_index%' ]
    fos_elastica.index.job:
        class: Elastica\Index
        factory: [ '@fos_elastica.client.default', 'getIndex' ]
        arguments: [ '%elasticsearch_job_index%' ]
    fos_elastica.index.company:
        class: Elastica\Index
        factory: [ '@fos_elastica.client.default', 'getIndex' ]
        arguments: [ '%elasticsearch_company_index%' ]
    App\Controller\Frontend\ElasticSearchController:
        arguments:
            $articleFinder: '@fos_elastica.index.article'
            $courseFinder: '@fos_elastica.index.course'
            $jobFinder: '@fos_elastica.index.job'
            $companyFinder: '@fos_elastica.index.company'