parameters:
    app_name: '%env(APP_NAME)%'
    app_env: '%env(APP_ENV)%'
    app_email: '%env(APP_EMAIL)%'
    email_address: '%env(EMAIL_ADDRESS)%'
    email_sender: '%env(EMAIL_SENDER)%'
    from_sender: '%env(EMAIL_SENDER)%'
    from_email: '%env(EMAIL_ADDRESS)%'
    cloudflare_r2_file_path: '%env(CLOUDFLARE_R2_FILE_PATH)%'
    app_page_template: '%env(APP_PAGE_TEMPLATE)%'
    app_page_widget_path: '%env(APP_PAGE_WIDGET_PATH)%'
    app_page_section_path: '%env(APP_PAGE_SECTION_PATH)%'
    app_page_widget_template: '%env(APP_PAGE_WIDGET_TEMPLATE)%'
    app_page_widget_gallery_path: '%env(APP_PAGE_WIDGET_GALLERY_PATH)%'
    app_page_section_gallery_path: '%env(APP_PAGE_SECTION_GALLERY_PATH)%'
    app_default_image: '%env(APP_DEFAULT_IMAGE)%'
    app_default_page_path: '%env(APP_DEFAULT_PAGE_PATH)%'
    app_menu_path: '%env(APP_MENU_PATH)%'
    app_setting_path: '%env(APP_SETTING_PATH)%'
    app_membership_package_path: '%env(APP_MEMBERSHIP_PACKAGE_PATH)%'
    netopia_username: '%env(NETOPIA_USERNAME)%'
    netopia_password: '%env(NETOPIA_PASSWORD)%'
    netopia_url: '%env(NETOPIA_URL)%'
    netopia_signature: '%env(NETOPIA_SIGNATURE)%'
    netopia_public_key_path: '%kernel.project_dir%/%env(NETOPIA_PUBLIC_KEY_PATH)%'
    netopia_private_key_path: '%kernel.project_dir%/%env(NETOPIA_PRIVATE_KEY_PATH)%'
    smart_bill_cif: '%env(SMARTBILL_CIF)%'
    smart_bill_invoice_series_name: '%env(SMARTBILL_INVOICE_SERIES_NAME)%'
    smart_bill_username: '%env(SMARTBILL_USERNAME)%'
    smart_bill_token: '%env(SMARTBILL_TOKEN)%'
    smart_bill_base_url: '%env(SMARTBILL_BASE_URL)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Mailer\TwigMailer:
       arguments: 
            $parameters: {from_sender: '%env(EMAIL_SENDER)%', from_email: '%env(EMAIL_ADDRESS)%'}
    App\Helper\MenuHelper:
        public: true
    App\Helper\MailHelper:
        arguments:
            $fromEmail: '%email_address%'
            $fromSender: '%email_sender%'
    App\EventSubscriber\PageNotFoundListener:
        arguments:
            $urlGenerator: '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Symfony\Component\Uid\Command\GenerateUuidCommand: ~
    App\Helper\FileUploader:
        arguments:
            $slugger: '@slugger'
            $accessKey: '%env(CLOUDFLARE_R2_ACCESS_KEY_ID)%'
            $secretKey: '%env(CLOUDFLARE_R2_SECRET_ACCESS_KEY)%'
            $region: '%env(CLOUDFLARE_R2_REGION)%'
            $endpoint: '%env(CLOUDFLARE_R2_ENDPOINT)%'
            $bucket: '%env(CLOUDFLARE_R2_BUCKET)%'
    App\Helper\NetopiaHelper:
        arguments:
            $username: '%netopia_username%'
            $password: '%netopia_password%'
            $baseUrl: '%netopia_url%'
            $signature: '%netopia_signature%'
    App\Helper\SmartBillAPIHelper:
        arguments:
            $cif: '%smart_bill_cif%'
            $invoiceSeriesName: '%smart_bill_invoice_series_name%'
            $username: '%smart_bill_username%'
            $token: '%smart_bill_token%'
            $baseUrl: '%smart_bill_base_url%'
